### ISSUE TITLE
Make price field optional during publishing [19Jan2018-1127]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/catalog-service#9] opened 2018-02-07 11:32 UTC
Path: 
 https://nimble-platform.salzburgresearch.at/nimble/frontend/#/catalogue/publish  

Description of the issue: 
1. Download of the template for product publishing is still not working. In the meanwhile we are checking the publishing one by one product.
2. Text field for description is too short (limited to round 150 chars.). This could be a longer text input such a text area.
3. In Trading tab, price is indicated as a mandatory field. In principle, this should be optional, or at least give the option to be hidden after publishing.
4. After clicking Add Property button, the new added custom property does not appear anywhere.
5. Also, Publish Product button appears disabled. This is a blocking issue.

**Comment by suatgonul** [comment] 2018-02-21 07:12
Description of the issue: 
1. Download of the template for product publishing is still not working. In the meanwhile we are checking the publishing one by one product. 
SG: This was a Firefox related issue about downloading the template. It's fixed now.

2. Text field for description is too short (limited to round 150 chars.). This could be a longer text input such a text area.

SG: Duplicate of: https://github.com/nimble-platform/catalog-service/issues/15

3. In Trading tab, price is indicated as a mandatory field. In principle, this should be optional, or at least give the option to be hidden after publishing.

SG: OK, will make the price optional.

4. After clicking Add Property button, the new added custom property does not appear anywhere.
SG: Duplicate of https://github.com/nimble-platform/catalog-service/issues/15

5. Also, Publish Product button appears disabled. This is a blocking issue.

SG: The button is disabled if an erroneous data entry exists

Since only the 3rd point is valid for this issue now. I'll change the name of the issue accordingly.

**Comment by dogukan10** [comment] 2018-03-19 12:36
Resolved with commit nimble-platform/frontend-service@593ad5a and c56e171

**Closed by dogukan10** 2018-03-19 12:36 UTC
Labels: bug, user experience
